package com.sams.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
public class PoHDTO {
    private Long poId;
    private Long orgId;
    private Long locationId;
    private String locationName;
    private String srNo;
    private String poNo;
    private Long poRevisionNo;
    private LocalDateTime poDt;
    private String poStatus;
    private String poType;
    private String contractType;
    private LocalDateTime contractStartDt;
    private LocalDateTime contractEndDt;
    private Long completionFlg;
    private Long businessPartnerId;
    private String businessPartnerName;
    private Long businessPartnerSiteId;
    private String businessPartnerSiteName;
    private Long billInfoId;
    private String billInfoName;
    private String billAddress1;
    private String billCity;
    private String billState;
    private String billCountry;
    private String billZipCode;
    private Long shipInfoId;
    private String shipInfoName;
    private String shipAddress1;
    private String shipCity;
    private String shipState;
    private String shipCountry;
    private String shipZipCode;
    private String contactPerson;
    private String shipTermsCd;
    private String shipModeCd;
    private String payTermsCd;
    private Long payTermDays;
    private String curCd;
    private Double exchRate;
    private String transporterName;
    private String transporterAddress;
    private LocalDateTime poReqDt;
    private Double totalAmt;
    private String localCurCd;
    private Double localBasicAmt;
    private Long customerId;
    private String customerName;
    private Double netTaxAmt;
    private Double basicAmt;
    private Double freightCharges;
    private Double handlingCharges;
    private Double otherCharges;
    private Double locFreightCharges;
    private Double locHandlingCharges;
    private Double locOtherCharges;
    private Double grandTotal;
    private Double localGrandTotal;
    private Long totalPoQty;
    private String termsConditions;
    private String cancelReason;
    private String rejectReason;
    private String createdBy;
    private LocalDateTime createdDt;
    private String updatedBy;
    private LocalDateTime updatedDt;
    private String remarks;
    private String billToContactPerson;
    private String billToContactPersonNo;
    private String shipToContactPerson;
    private String shipToContactPersonNo;
    private Long workFlowProcessStatusId;
    private String billToContactPerson1;
    private String billToContactPersonNo1;
    private String shipToContactPerson1;
    private String shipToContactPersonNo1;
    private Boolean isFromCmms;
    private Boolean advanceAmtRequired;
    private Double advanceAmtValue;
    private String osprTermsAndConditions;
    private String gstNumber;
    private LocalDateTime expectedArrivalDate;
    private String suppilerContactPersonName;
    private String supplierContactNumber;
    private String smApprovedLoginId;
    private LocalDateTime smApprovedDate;
    private String vpApprovedLoginId;
    private LocalDateTime vpApprovedDate;
    private Double advancePaymentPercentage;
}