export enum allassetStatus {
    IN_USE = 1,
    NOT_IN_USE = 2,
    RETIRED = 3,
    MISSING = 4 ,
    NEW = 5 ,
    IN_STOCK = 6,
    NOT_IN_STOCK = 7,
}

export enum allWorkflowStatus {
  WO_INSTALLATION = 1,
  WO_BD = 2,
  CONDEMNATION = 3,
  PR = 4,
  PO = 5,
  GATE_PASS = 6,
  LOAN = 7,
  PRE_INWARD = 8,
  WO_HANDOVER = 9,
  ASSET_CREATE = 10,
  WO_PM = 11,
  WO_PA = 12,
  WO_QA = 13,
  CONTRACT = 14,
  RETIREMENT = 15,
  DISPOSAL = 16,
  SALVAGE = 17,
  LOAN_RETURNS = 18,
  STOCK_TRANSFER = 19,
  STOCK_ALLOCATE = 20,
  ASSET_RELOCATION = 21,
  STOCK_INDENT = 22,
  ITEM_APPROVAL = 23,
  GRN_APPROVAL = 24,
  ASSET_PHY_AUDIT = 25,
  WF_SUPPLIER_INVOICE = 26,
  RTV_APPROVAL = 27,
  ASSET_CODE_CHANGE = 28,
  PO_CONTRACT = 29,
  SCRAPPED = 30,
}

export enum allPreInwardStatus {
  APPROVAL_PENDING = 1001,
  AWAITING_FOR_ARRIVAL = 1002,
  PARTIALLY_IN_STOCK = 1003,
  IN_STOCK = 1004,
  REJECTED = 1005,
}

export enum allAssetCreateStatus {
  IN_PROGRESS = 1101,
  REJECTED = 1102,
}

export enum allAssetRetirmentStatus {
  AWAITING_FOR_RETAIR_APPROVAL = 1201,
  AWAITING_FOR_SALVAGE_APPROVAL = 1202,
  AWAITING_FOR_DISPOSAL_APPROVAL = 1203,
  RETIREMENT_APPROVED = 1204,
  RETIREMENT_REJECTED = 1205,
  SALVAGE_REJECTED = 1206,
  DISPOSE_REJECTED = 1207,
  SALVAGED = 1208,
  DISPOSED = 1209,
  RETIRED = 1210,
  SCRAPPED = 1211,
  AWAITING_FOR_SCRAP_APPROVAL = 1212,
  SCRAP_REJECTED = 1213,
}

export enum allAssetTransferStatus {
  AWAITING_FOR_RELOCATION_APPROVAL = 1301,
  RELOCATION_APPROVED = 1302,
  RELOCATION_REJECTED = 1303,
}

export enum allAssetAuditStatus {
  SCHEDULED = 1401,
  IN_PROGRESS = 1402,
  WAITING_FOR_APPROVAL = 1403,
  APPROVED = 1404,
  REJECTED = 1405,
  FAILED = 1406,
}

export enum allGatePassStatus {
  GATE_PASS_REQUESTED = 1501,
  GATE_PASS_APPROVED = 1502,
  GATE_PASS_REJECTED = 1503,
  GATE_PASS_CLOSED = 1504,
}

export enum allloanStatus {
  REQUESTED_FOR_LOAN = 1601,
  LOAN_APPROVED = 1602,
  LOAN_REJECTED = 1603,
  REQUEST_FOR_RETURN = 1604,
  RETURNED = 1605,
  OVER_DUE = 1606,
  PARTIALLY_RETURNED = 1607,
  AWAITING_FOR_RECEIVED_BY_APPROVAL = 1608,
  LOANED = 1609,
  AWAITING_FOR_RETURN_APPROVAL = 1610,
  RETURN_REQUEST_APPROVAL = 1611,
  LOAN_RETURNED = 1612,
  RETURN_REJECTED = 1613,
}

export enum allContractStatus {
  CONTRACT_APPROVAL_PENDING = 1701,
  CONTRACT_APPROVED = 1702,
  CONTRACT_REJECTED = 1703,
  CONTRACT_CANCELLED = 1704,
  CONTRACT_TRMINATED = 1705,
  CONTRACT_EXPIRED = 1706,
  CONTRACT_COMPLETED = 1707
}

export enum allAssetAgeCriteriaStatus {
  PURCHASE_DATE = 1,
  RECEIVED_DATE = 2,
  INSTALLATION_DATE = 3
}

export enum allAssetStatusType {
  AST_STS_TYP_UNASSIGNED = 1,
  AST_STS_TYP_ASSIGNED = 2,
  AST_STS_TYP_DISCARDED = 3
}

export enum allAssetCondition {
  AST_CDN_NEW = 1,
  AST_CDN_GOOD = 2,
  AST_CDN_POOR = 3,
  AST_CDN_DAMAGED = 4,
  AST_CDN_MISSING = 5
}

export enum allBusinessPartnerRoles {
  SUPPLIER = 1,
  CUSTOMER = 2,
  MANUFACTURER = 3,
  SERVICE_PROVIDER = 4
}

export enum allAssetCodeChangeStatus {
  AWAITING_FOR_CHANGE_ASSET_CODE_APPROVAL = 1901,
  CHANGE_ASSET_CODE_APPROVED = 1902,
  CHANGE_ASSET_CODE_REJECTED = 1903
}

