export const ModelScreenTabs = [
  {
    name: 'model_basic_info',
    lable: 'COMMON_BASIC_INFORMATION',
    value: true
  }, {
    name: 'model_image',
    lable: 'MODEL_IMAGE',
    value: true
  }, {
    name: 'model_custom_fields',
    lable: 'MODEL_CUSTOM_FIELDS',
    value: true
  }, {
    name: 'model_depreciation',
    lable: 'MODEL_DEPRICIATION',
    value: true
  }, {
    name: 'asset_maintenance_scheduling',
    lable: 'ASSET_MAINTENANCE_SCHEDULING',
    value: true
  }, {
    name: 'child_model',
    lable: 'CHILD_MODEL',
    value: true
  }, {
    name: 'model_solution_bank',
    lable: 'MODEL_SOLUTION_BANK',
    value: true
  }, {
    name: 'model_items',
    lable: 'MODEL_ITEMS',
    value: true
  }, {
    name: 'model_document',
    lable: 'MODEL_DOCUMENT',
    value: true
  }, {
    name: 'model_self_analysis',
    lable: 'MODEL_SELF_ANALYSIS',
    value: true
  }, {
    name: 'model_additional_info',
    lable: 'MODEL_ADDITIONAL_INFO',
    value: true
  }, {
    name: 'sr_check_points',
    lable: 'SR_CHECK_POINTS',
    value: true
  }, {
    name: 'menu_inventory_module',
    lable: 'MENU_INVENTORY_MODULE',
    value: true
  }, {
    name: 'technical_specelist',
    lable: 'TECHNICAL_SPECELIST',
    value: true
  }
]