export enum processList {
	PRE_INWARD = 10,
	ASSET_CREATE = 11,
	ASSET_RETIREMENT = 12,
	ASSET_TRANSFER = 13,
	ASSET_AUDIT = 14,
	ASSET_GATE_PASS = 15,
	ASSET_LOAN_AND_RETURN = 16,
  	ASSET_CONTRACT =17,
	ASSET_ASSIGNMENT=18,
	ASSET_CODE_CHANGE = 19
}
